-- Migration: 00011_add_ai_report_to_analysis
-- Description: Add ai_report column to store Claude AI analysis markdown
-- Author: Dex (Dev Agent)
-- Date: 2026-04-03

ALTER TABLE public.analysis_history
  ADD COLUMN ai_report TEXT;

COMMENT ON COLUMN public.analysis_history.ai_report IS 'Markdown report generated by Claude AI analysis. Stored to avoid re-generating.';

-- Allow updates on analysis_history (needed to save AI report after streaming completes)
CREATE POLICY "analysis_update" ON public.analysis_history
  FOR UPDATE USING (
    tenant_id = public.get_user_tenant_id()
    AND public.has_permission('mining.view')
  );
